version: "3"
services:
  serve:
    container_name: AdminLTE-Starting-Kit-Nextjs
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    expose:
      - 3000
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000